### PR TITLE
Upgrade Gradle to 7.4 & AGP to 7.1.1 (& Disable Jetifier & Min SDK Version)

### PR DESCRIPTION
**Pull request by ParaskP7**
This PR is part of [Upgrade Gradle to 7.4 & AGP to 7.1.1 (& Disable Jetifier)](https://github.com/WordPress/gutenberg/pull/39097) PR. There are `13` libraries that are upgraded to `Gradle 7.4` & `AGP 7.1.1` (& `Disable Jetifier`).

-----

All those PRs follow the general outline below:
- `Gradle` version upgraded to `7.3.3` with the `./gradlew wrapper --gradle-version=7.3.3 --distribution-type=all` command.
- `AGP` version upgrade to `7.0.4` (see `android/settings.gradle.kts` change).
- Build output diff:
  - To identify and fix new warnings/errors that got added.
  - To identify and verify old warnings/errors that got removed.
- Lint output diff
  - To identify and fix new warnings/errors that got added.
  - To identify and verify old warnings/errors that got removed.
- The above 4 steps were redone with a follow-up update to `Gradle 7.4` & `AGP 7.1.1`.
- Jetifier drop (see `android/gradle.properties` change).
- Version bump to `1.9.0-wp-2` (see `package.json`).
- Tarball update to `1.9.0-wp-2` (see `react-native-clipboard-clipboard-1.9.0-wp-2.tgz`).
- The build was also verified through [Jitpack](https://jitpack.io/#wordpress-mobile/react-native-clipboard) (see [build.log](https://jitpack.io/com/github/wordpress-mobile/react-native-clipboard/update~gradle-to-7.3.3-agp-to-7.0.4-v1.9.0-g773d150-14/build.log)).

This PR also included the following changes:
- Update min SKD `21` (see `android/gradle.properties` change).

-----

**To test - Now**

These changes can be tested as part of the [gutenberg PR](https://github.com/WordPress/gutenberg/pull/39097) which is [updated to use the temporarily non-tagged node module project dependencies](https://github.com/WordPress/gutenberg/pull/39097/commits/d10243401c1ef73be0bcc74023adba25c4787b56) generated with these changes.

**To test - Later** ⚙️

These changes can be tested as part of the [gutenberg-mobile PR ⚙️](TODO) or [WordPress-Android PR ⚙️](TODO) which is [updated to use the bundle ⚙️](TODO) generated with these changes.

FYI: It's best to leave the testing step to the [gutenberg PR](https://github.com/WordPress/gutenberg/pull/39097) review since even if these PRs are merged, they won't impact anything until [the package.json file is updated](https://github.com/WordPress/gutenberg/pull/39097/commits/d10243401c1ef73be0bcc74023adba25c4787b56). Worst case scenario, a follow up PR will get opened to fix any issues that are found during testing.

-----

**Follow up**

Once these PRs are merged in, a new tag will get created for each library and [the package.json file will be again updated accordingly](https://github.com/WordPress/gutenberg/pull/39097/commits/d10243401c1ef73be0bcc74023adba25c4787b56).

### CODE REVIEW

**Review by oguzkocer — APPROVED** [review]

**Comment by ParaskP7** [comment]
👋 @hypest !

Can you verify that [this change I did here](https://github.com/wordpress-mobile/react-native-clipboard/pull/2/commits/b09baa4781347ca37207d2c83aae64d5c5da32cf), which updates the `minSdkVersion` to `21`, is actually correct? 🙇 

PS: I did that because otherwise Lint fails for both, this repo and the `react-native-bridge` module within the [gutenberg](https://github.com/WordPress/gutenberg) repo.

**Comment by hypest** [comment]
> Can you verify that [this change I did here](https://github.com/wordpress-mobile/react-native-clipboard/pull/2/commits/b09baa4781347ca37207d2c83aae64d5c5da32cf), which updates the minSdkVersion to 21, is actually correct? 🙇

Happy to help @ParaskP7 ! Can you share the GB PR or the WPAndroid PR to test it out? Thanks!

**Comment by ParaskP7** [comment]
> Happy to help @ParaskP7 ! Can you share the GB PR or the WPAndroid PR to test it out? Thanks!

Thank you @hypest ! You can test by running Lint on this repo and see the outcome if you revert [my change](https://github.com/wordpress-mobile/react-native-clipboard/pull/2/commits/b09baa4781347ca37207d2c83aae64d5c5da32cf) from `21` to `16`. As far as testing it, with either a `GB PR` or `WPAndroid PR`, unfortunately those are not ready yet. 🤔 

PS: I am currently working on creating the `GB PR`. I hope this will help you with your testing. I'll let you know when it gets available. 👍

**Comment by hypest** [comment]
Thanks for the testing info @ParaskP7 , I verified it on my side that lint is not complaining with the `16`->`21` bump.

I wonder if this is a change we should push upstream 🤔 , wdyt?

**Comment by ParaskP7** [comment]
> Thanks for the testing info @ParaskP7 , I verified it on my side that lint is not complaining with the 16->21 bump.

Thanks for verifying that @hypest ! 🙇 

> I wonder if this is a change we should push upstream 🤔 , wdyt?

As I explained on [my commit message](https://github.com/wordpress-mobile/react-native-clipboard/pull/2/commits/b09baa4781347ca37207d2c83aae64d5c5da32cf), since all other such forked repos are already pointing to a `minSdkVersion` of `21` instead of `16`, we should at least match that expectation on the node module folk libraries level. I am also seeing all the `gutenberg` Android modules are pointing to `minSdkVersion` of `21`.

In addition to that, on the `WPAndroid` side, we are looking at a `minSdkVersion` of `24`, which mean that at least that client would no longer support `minSdkVersion` of `21`, let along `minSdkVersion` of `16`. All that makes me think that we should drop support for `minSdkVersion` of `16` for this repo and actually later on we might want to even drop support for `minSdkVersion` of `21` in favor of `minSdkVersion` of `24`. Wdyt? 🤔

**Comment by hypest** [comment]
Verified that the lint error is related to the gradle and AGP update anyway so, pushing the minSDK change upstream would also require pushing all the android build diff so far, and I think that's outside the scope for the effort here. So, I'm cool from my side to contain the changes here.

**Comment by ParaskP7** [comment]
> Verified that the lint error is related to the gradle and AGP update anyway so, pushing the minSDK change upstream would also require pushing all the android build diff so far, and I think that's outside the scope for the effort here. So, I'm cool from my side to contain the changes here.

So, just to get this right @hypest you too think that this change of `minSdkVersion`, from `16`, to `21`, most probably shouldn't cause any problems to `GB` or its clients, like `WPAndroid`, so this is a 👍 to proceed, right?

PS: We will anyway be testing `GB` and `WPAndroid` extensively afterwards to verify that all these changes are okay. If, during out testing, we will find issue related to that we can revert it anyway.

**Comment by hypest** [comment]
Oh, yeah, I don't expect the minSDKVersion bump to 21 to be a problem for Gutenberg, especially since it's already the minimum for RN itself. Besides, as you mention, we'll try it more via the WPAndroid and Gutenberg PRs.

**Comment by hypest** [comment]
We are [retiring this repo](https://github.com/wordpress-mobile/react-native-clipboard/pull/3) so, no need for further work on this PR. Thank you for the hard work on this this far folks! ❤️

**Pull request closed without merging**
